### ISSUE TITLE
Correção de histórias de usuário

### ISSUE THREAD

**Issue by lucasfs1007** [Requisitos-de-Software/2022.2-GoogleMaps#107]

**Comment by lucasfs1007** [comment]
- [ ] Redifinir os epicos para que fiquem mais bem definidos com as histórias de usuário --> métrica do grupo que avaliou

**Comment by lucasfs1007** [comment]
- [ ] Deve-se alterar o nome das histórias 1 e 4 pois elas seguem o mesmo nome com funcionalidades diferentes.
- [ ] Deve-se validar as histórias de usuário com usuários (uma entrevista talvez fosse o ideal)

**Comment by iagoscm** [comment]
- A história 1 refere-se à visualização do mapa como um todo, já a história 4 refere-se à localizaçoes fixas presentes neste mapa;
- Não possuímos tempo hábil para validar estas histórias além da entrevista já feita com a usuária em relação aos requisitos finais.
