### ISSUE TITLE
Correção Especificação Suplementar

### ISSUE THREAD

**Issue by lucasfs1007** [Requisitos-de-Software/2022.2-GoogleMaps#109]

**Comment by lucasfs1007** [comment]
- [ ] Falta linkagem e versionamento --> métricas do grupo que avaliou
- [ ] Falta informações sobre usabilidade --> métricas do grupo que avaliou
- [ ] Falta informações sobre segurança de uso --> métricas do grupo que avaliou

**Comment by lucasfs1007** [comment]
- [ ] Deve-se acresentar informações acerca de confiança na conficiabilidade
- [ ] Deve-se acresentar informações sobre satisfação.
- [ ] Deve-se linkar  os léxicos dentro do artefato.

**Comment by alexianaa** [comment]
- Existe uma especificação suplementar de confiabilidade que fala sobre segurança a falhas (margem de erro da localização e áreas de alerta.
- Existe uma especificação sobre usabilidade, o que pode ser considerado informaçãoes sobre satisfação?
- foi linkado os casos de uso, os requisitos que são citados na página e os léxicos que se assemelhassem a alguma situação, mas os léxicos não foram usados na construção do artefato.
