### ISSUE TITLE
Correções Backlog

### ISSUE THREAD

**Issue by lucasfs1007** [Requisitos-de-Software/2022.2-GoogleMaps#136]
- [x] Adicionar numerações adequadas das tabelas.
- [x] adicionar o indíce da bibliografia
- [x] correção de ortografia na introdução (está escrito usuárias)
- [x] As features relacionadas com "Navegação" faz mais sentido com o épico de encontrar a melhor rota, e a feature de "Pesquisa e filtragem" faz mais sentido com o épico de encontrar destino. Pois primeiro precismos pesquisar para encontrar o destino e depois de encontra-lo vamos poder de fato traçar as melhores rotas para este destino. --> tão invertidas
- [x] adicionar hiperlinks para as histórias de usuário e priorização.

**Comment by luciano-freitas-melo** [comment]
Issue fechada no PR #143
