### ISSUE TITLE
Conclusão final

### ISSUE THREAD

**Issue by lucasfs1007** [Requisitos-de-Software/2022.2-GoogleMaps#156]
--> Nova aba chamada "Conclusão"
- [x] Apresentação do cronograma final --> linkagem
- [x] Apresentação dos resultados
- [x] Apresentação das etapas do projeto: Apresentar do que se trata cada aba e linkagem
- [x] Tabela de artefatos e os autores e revisores dos mesmos --> linkagem
- [x] Tabela com os métodos de verificação e validação --> linkagem
- [x] Tabela apresentando quais ferramentas foram utilizadas em cada etapa --> linkagem
- [x] Tabela com dificuldades e facilidades de cada membro da equipe

**Comment by luciano-freitas-melo** [comment]
Issue fechada no PR #163
