### ISSUE TITLE
Correções da entrega 1

### ISSUE THREAD

**Issue by alexianaa** [Requisitos-de-Software/2022.2-GoogleMaps#30]
- [x] Padronizar os históricos de versão.
- [x] Adicionar referências bibliográficas em todas as páginas no formato ABNT: SOBRENOME, Nome Abreviado. Título: subtítulo (se houver). Edição (se houver). Local de publicação: Editora, ano de publicação. -> @iagoscm 
- [x] Adicioanar fonte nas tabelas do conograma como "Fonte: Elaboração Própria".
- [x] Adicionar texto chamando as imagens/tabelas. -> @luciano-freitas-melo 
- [ ] Adicionar cronograma executado e planejado. -> @luciano-freitas-melo e @marcusmartinss 
- [x] Definir responsáveis e revisores em todas as tarefas do cronograma. -> @iagoscm 
- [x] Definir e adicionar ferramenta de elaboração de personas. -> @iagoscm 
- [ ] Adicionar aba `padronização` em planejamento, contendo a política de branches e commits, padrão de histórico de versão, padrão de issue e pull request. -> @luciano-freitas-melo

**Comment by luciano-freitas-melo** [comment]
Os históricos de versão foram padronizados por @lucasfs1007 da seguinte forma e na ordem:
- Data: dd/mm/aaaa
- Versão: X.0, sendo X a versão do artefato, em ordem crescente e iniciando em 1.0
- Descrição: Quais foram as implementações/alterações da nova versão
- Autor: O nome e um sobrenome dos membros que fizeram a versão
- Revisores: O nome e um sobrenome dos membros que revisaram o documento

**Comment by iagoscm** [comment]
@luciano-freitas-melo bom deixar anotado no planejamento

**Comment by luciano-freitas-melo** [comment]
### Outras padronizações:
#### Legendas e Fonte(source) de imagens e tabelas
De acordo com as normas ABNT, as **legendas devem ficar acima** da imagem/tabela, enquanto a **fonte deve ficar abaixo** das respectivas imagens e tabelas.

OBS: Deve-se ficar atento que qualquer tabela ou imagem inserida do projeto deve ser **mencionada no texto**.

#### Parágrafos
Qualquer parágrafo de texto que for adicionado em quaisquer artefatos devem ter um espaçamento inicial. Para isso, é preciso utilizar o comando: `&emsp;&emsp;` no ínicio do parágrafo.
