### ISSUE TITLE
correções de quebra de imagem

### ISSUE THREAD

**Issue by lucasfs1007** [Requisitos-de-Software/2022.2-GoogleMaps#31]
corrigir as imagens que estão quebradas ao subir para o site

**Comment by luciano-freitas-melo** [comment]
- O problema era a utilização da tag html de `<img>`, que não funciona corretamente quando ocorre o deploy para o gitpages. Para resolver o problema foi adicionado uma extensão do mkdocs material que possibilita utilizar propriedades html dentro do markdown, mais informações [nesse link](https://squidfunk.github.io/mkdocs-material/reference/images/#image-alignment)
- Como o problema só aparecia no deploy do pages, foi preciso realizar os **commits diretamente na main**, segue os links:
- 99ef68b16c7b99caf723fb29445a363d15f7b17a
- 3c19bf213bc527f16557576f42ce1428ec9839d6
