### ISSUE TITLE
Especificação dos léxicos

### ISSUE THREAD

**Issue by iagoscm** [Requisitos-de-Software/2022.2-GoogleMaps#37]
- [x] Criação da página dos léxicos
- [ ] Definição do usuário presente nos Léxicos
- [x] Os léxicos possuem ligações entre si
- [x] Os léxicos utilizam a estrutura de dicionário (verbo, objeto, estado)
- [x] Histórico de versão

**Comment by lucasfs1007** [comment]
revisor : Lucas
