### ISSUE TITLE
Criação do diagrama de casos de uso

### ISSUE THREAD

**Issue by iagoscm** [Requisitos-de-Software/2022.2-GoogleMaps#39]
- [ ] O ator principal está do lado esquerdo do sistema no diagrama de caso de uso
- [ ] Os atores estão fora da caixa de limite do sistema no diagrama de caso de uso
- [ ] A especificação do diagrama de caso de uso (com Nome, Descrição, Atores, Pré-Condição,PósCondição, Fluxo Principal, Fluxo Alternativo e Fluxo de Exceção etc.)
- [ ] A participação do cliente e/ou persona na validação do Diagrama 
- [ ] Histórico de Versão

**Comment by lucasfs1007** [comment]
revisor : iago
