### ISSUE TITLE
Especificação suplementar

### ISSUE THREAD

**Issue by iagoscm** [Requisitos-de-Software/2022.2-GoogleMaps#40]
- [x] Criação da página da especificação suplementar
- [ ] O artefato segue o modelo FURPS+?
- [ ] O documento especifica o tempo de resposta, no Desempenho
- [ ] O documento especifica qual plataforma o aplicativo pode ser executado
- [ ] Todos os requisitos podem ser testados (RF e RNF)
- [ ] Histórico de versão

**Comment by lucasfs1007** [comment]
revisor: Marcus
