### ISSUE TITLE
Correções de Personas e perfil de usuário parte 2

### ISSUE THREAD

**Issue by lucasfs1007** [Requisitos-de-Software/2022.2-GoogleMaps#58]
Essa issue é referente a correções sugeridas pelo professor e monitor após a entrega 2.
- [ ] Criar um 3° grupo de usuários que faça referência as 3 persnonas.
- [ ] Adiciona nova bibliografia sugerida.
- [ ] Ajustar a explicação para a quantidade de membros no elenco de personas.
- [ ] Histórico de versões

**Comment by alexianaa** [comment]
Quando você finalizar as tasks da issue não esquece de marcar como completo aqui
