### ISSUE TITLE
pré-rastrabilidade dos requisitos

### ISSUE THREAD

**Issue by lucasfs1007** [Requisitos-de-Software/2022.2-GoogleMaps#65]
"Faltou a coluna com o id do
requisito em todos os artefatos
de elicitação, para que assim
vocês consigam saber de qual
técnica veio aquele requisito
"

**Comment by alexianaa** [comment]
- [ ] Criar tabela de requisitos com todos os requisitos de todas as técnicas 
- [ ] Especificar fonte de técnica dos requisitos das priorizações (entrevistas)
