### ISSUE TITLE
Aprimorar a priorização de requisitos

### ISSUE THREAD

**Issue by alexianaa** [Requisitos-de-Software/2022.2-GoogleMaps#68]
- [x] Criar uma tabela só com todos os requisitos na página de priorização
- [x] Aplicar as técnicas de priorização
- [x] Adicionar um requisito que aborde a ação de criar um estabelecimento
- [ ] Colocar explicação de ações mais complicadas em "Definições, acrônimos e abreviações"

**Comment by marcusmartinss** [comment]
Seria interessante termos requisitos para estabelecimentos que não existem mais ou se mudaram de certa localidade.
