### ISSUE TITLE
Critérios de aceitação

### ISSUE THREAD

**Issue by iagoscm** [Requisitos-de-Software/2022.2-GoogleMaps#82]
- [x] Definir critérios de aceitação
- [x] Validação para saber se as histórias de usuário podem ser testadas

**Comment by marcusmartinss** [comment]
Foi removido da checklist da issue o critério "Participação do cliente ou persona (melhor com vídeos)" para seguir o padrão dos grupos anteriores e pela dificuldade de se encontrar um usuário ao final de ano.

**Comment by marcusmartinss** [comment]
- [ ] Completar critérios de aceitação das US 17-33
