### ISSUE TITLE
Validação da modelagem de requisitos Cenários grupo "Star +" 

### ISSUE THREAD

**Issue by lucasfs1007** [Requisitos-de-Software/2022.2-GoogleMaps#90]

**Comment by lucasfs1007** [comment]
Em uma nova aba deve contar uma tabela em que se verifique se o grupo executou tais atividades :
- [ ]  Histórico de versão padronizado
- [ ] Autores e revisores de cada artefato
- [ ]  Vídeo de apresentação não listado no youtube
- [ ] Texto contendo introdução aos artefatos
- [ ]  Cronograma exececutado
- [ ] As atas de reunião
- [ ] Gravações do grupo
- [ ]  As especificações dos cenários para o projeto
- [ ]  Os cenários possuem os elementos básicos de um cenário (Título, Metas/Objetivo, Contexto,
Atores, Recursos, Exceção e Episódios)
- [ ]  As especificações dos Léxicos?
- [ ] A definição do usuário nos Léxicos?
- [ ] Os léxicos possuem ligações entre si
- [ ]  Os léxicos utilizam a estrutura de dicionário (verbo, objeto, estado)?
- [ ]  A especificação dos caso de uso?
- [ ]  Os atores principais e atores secundários no diagrama de caso de uso?
- [ ]  O ator principal está do lado esquerdo do sistema no diagrama de caso de uso?
- [ ]  Os atores estão fora da caixa de limite do sistema no diagrama de caso de uso?
- [ ] A especificação do diagrama de caso de uso (com Nome, Descrição, Atores, Pré-Condição,PósCondição, Fluxo Principal, Fluxo Alternativo e Fluxo de Exceção etc.)?
- [ ] A participação do cliente e/ou persona na validação do Diagrama de Casa de Uso?
- [ ] A especificação suplementar?
- [ ] O artefato segue o modelo FURPS+?
- [ ] O documento especifica o tempo de resposta, no Desempenho?
- [ ] O documento especifica qual plataforma o aplicativo pode ser executado?
- [ ]  - Todos os requisitos podem ser testados (RF e RNF)?

**Comment by lucasfs1007** [comment]
Lucas vai começar na frente

**Comment by luciano-freitas-melo** [comment]
Issue resolvida no PR #97
